[package]
name = "rust-hello"
version = "0.1.0"
authors = ["Daniel Axtens <dja@axtens.net>"]
edition = "2018"

[lib]
crate_type = ["staticlib"]

[profile.release]
panic="abort"
lto = true

#[target]
#"features": "-mmx,-sse,+soft-float"

[dependencies]
cty = "^0.2"


